export const moviesCardsData = [
  {
    name: '33 слова о дизайне',
    link: 'https://i.ibb.co/QKsZPzY/pic-COLOR-pic1.png',
    duration: 107,
    like: true,
    _id: 1,
  },
  {
    name: 'Киноальманах «100 лет дизайна»',
    link: 'https://i.ibb.co/SnDmWgj/pic-COLOR-pic2.png',
    duration: 94,
    like: false,
    _id: 2,
  },
  {
    name: 'В погоне за Бенкси',
    link: 'https://i.ibb.co/cFMFPh5/pic-COLOR-pic3.png',
    duration: 125,
    like: false,
    _id: 3,
  },
  {
    name: 'В погоне за Бенкси',
    link: 'https://i.ibb.co/cFMFPh5/pic-COLOR-pic3.png',
    duration: 125,
    like: false,
    _id: 4,
  },
  {
    name: 'Баския: Взрыв реальности',
    link: 'https://i.ibb.co/tbz60tV/pic-COLOR-pic4.png',
    duration: 89,
    like: false,
    _id: 5,
  },
  {
    name: 'Бег это свобода',
    link: 'https://i.ibb.co/2YPwn6S/pic-COLOR-pic5.png',
    duration: 71,
    like: false,
    _id: 6,
  },
  {
    name: 'Книготорговцы',
    link: 'https://i.ibb.co/K0hhTqJ/pic-COLOR-pic6.png',
    duration: 85,
    like: false,
    _id: 7,
  },
  {
    name: 'Когда я думаю о Германии ночью',
    link: 'https://i.ibb.co/kSJmWx1/pic-COLOR-pic7.png',
    duration: 130,
    like: false,
    _id: 8,
  },
  {
    name: 'Gimme Danger: История Игги и The St...',
    link: 'https://i.ibb.co/x8CDvnL/pic-COLOR-pic8.png',
    duration: 112,
    like: true,
    _id: 9,
  },
  {
    name: 'Книготорговцы',
    link: 'https://i.ibb.co/K0hhTqJ/pic-COLOR-pic6.png',
    duration: 85,
    like: false,
    _id: 10,
  },
  {
    name: 'Книготорговцы',
    link: 'https://i.ibb.co/K0hhTqJ/pic-COLOR-pic6.png',
    duration: 85,
    like: false,
    _id: 11,
  },
  {
    name: 'Книготорговцы',
    link: 'https://i.ibb.co/K0hhTqJ/pic-COLOR-pic6.png',
    duration: 85,
    like: false,
    _id: 12,
  },
];

/* export let savedMoviesCardsData = [
  {
    name: '33 слова о дизайне',
    link: 'https://i.ibb.co/QKsZPzY/pic-COLOR-pic1.png',
    duration: 107,
    _id: 1,
  },
  {
    name: 'Киноальманах «100 лет дизайна»',
    link: 'https://i.ibb.co/SnDmWgj/pic-COLOR-pic2.png',
    duration: 94,
    _id: 2,
  },
  {
    name: 'В погоне за Бенкси',
    link: 'https://i.ibb.co/cFMFPh5/pic-COLOR-pic3.png',
    duration: 125,
    _id: 3,
  },
  {
    name: 'В погоне за Бенкси',
    link: 'https://i.ibb.co/cFMFPh5/pic-COLOR-pic3.png',
    duration: 125,
    _id: 4,
  },
]; */
